CREATE DATABASE DB_CITA;

USE DB_CITA;

CREATE TABLE PACIENTE(
	ID INT NOT NULL PRIMARY KEY IDENTITY, 
	DPI VARCHAR(15) NOT NULL,
	PASS VARCHAR(12) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	GENERO CHAR(1) NOT NULL,
	FEC_NACIMIENTO DATETIME NOT NULL, 
	DIRECCION VARCHAR(25) NOT NULL, 
	TIPO_SANGRE CHAR(1) NOT NULL, 
	NUM_SERGURO_MED VARCHAR(12) NOT NULL
);

CREATE TABLE ROLES(
	ID INT NOT NULL PRIMARY KEY IDENTITY, 
	DESCRIPCION VARCHAR(25) NOT NULL
);

CREATE TABLE TRABAJADORES(
	ID INT NOT NULL PRIMARY KEY IDENTITY, 
	USUARIO VARCHAR(25) NOT NULL, 
	PASS VARCHAR(25) NOT NULL,
	NOMBRE VARCHAR(25) NOT NULL, 
	APELLIDO VARCHAR(25) NOT NULL, 
	DPI VARCHAR(25) NOT NULL,
	TELEFONO VARCHAR(12) NOT NULL,
	IDROLE INT NOT NULL, 
	FOREIGN KEY (IDROLE) REFERENCES ROLES(ID)
);

CREATE TABLE CITA(
	ID INT NOT NULL PRIMARY KEY IDENTITY, 
	FECHA DATE NOT NULL,
	DESCRIPCION VARCHAR(4000),
	HORA TIME NOT NULL,
	IDPACIENTE INT NOT NULL,
	IDTRABAJADOR INT NOT NULL,
	CREATEBY VARCHAR NOT NULL,
	CREATEDATE DATETIME NOT NULL
	FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE(ID),
	FOREIGN KEY (IDTRABAJADOR) REFERENCES TRABAJADORES(ID)
);

CREATE TABLE DETALLE_CITA(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	IDCITA INT NOT NULL,
	NOM_MED VARCHAR(25) NOT NULL,
	DESCRIPCION VARCHAR(4000) NOT NULL
);
